### ISSUE TITLE
Home Assistant integration, entity will not work in automation

### ISSUE THREAD

**Issue by bertiebeez** [nutechsoftware/alarmdecoder-webapp#90]
I have a AD2PI recently purchased. This is working fine with Home assistant. I am trying to intergate a few 433mhz sensors and have them enabled by an automation that detects when the Alarm panel is armed. The automation does not work.
Do you have any idea what could be the issue. Here is the code for the automation. I have tried also to trigger it on the state of the alarm panel rather than the "READY" attribute. Neither one will work.

```
- id: '1611450843281'
  alias: Enable 433mhz alarms from AD2pi
  description: ''
  trigger:
  - platform: state
    to: 'false'
    from: 'true'
    entity_id: alarm_control_panel.alarm_panel
    attribute: ready
  condition: []
  action:
  - condition: state
    state: 'on'
    entity_id: input_boolean.alarm_enable
  mode: single
```
